on:
  workflow_dispatch:
    inputs:
      fe_branch:
        description: 'The FE branch name to deploy (e.g., pr-123)'
        default: 'main'

permissions:
  id-token: write
  contents: read

jobs:
  update-preview:
    name: Update Vercel Preview for FE branch
    runs-on: ubuntu-latest
    steps:
      - name: Upsert Vercel env var for this FE branch (Preview target)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          KEY='VITE_API_URL'
          VALUE='https://api.pr-${{ github.event.inputs.fe_branch }}.deploy-preview.mrdibre.com'
          BRANCH='${{ github.event.inputs.fe_branch }}'
          echo "Setting $KEY=$VALUE for branch $BRANCH in Vercel project $VERCEL_PROJECT_ID"
          curl -s -X POST "https://api.vercel.com/v10/projects/$VERCEL_PROJECT_ID/env?teamId=$VERCEL_ORG_ID" \
            -H "Authorization: Bearer $VERCEL_TOKEN" -H "Content-Type: application/json" \
            -d "{\"key\":\"$KEY\",\"value\":\"$VALUE\",\"type\":\"plain\",\"target\":[\"preview\"],\"gitBranch\":\"$BRANCH\"}" \
          | jq '.'

      - name: Trigger FE Preview deployment for that branch
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          # Create a new deployment from a Git ref (branch) for the FE project
          # Docs: Create Deployment API (POST /v13/deployments)
          curl -s -X POST "https://api.vercel.com/v13/deployments?teamId=$VERCEL_ORG_ID" \
            -H "Authorization: Bearer $VERCEL_TOKEN" -H "Content-Type: application/json" \
            -d '{
              "target": "preview",
              "gitSource": {
                "type": "github",
                "ref": "'"${{ github.event.inputs.fe_branch }}"'",
              }
            }' | jq '{url:.url, state:.readyState, id:.id}'
